
package com.acec.wgt.service.sms;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SMSServiceImpl", targetNamespace = "http://HLimpl.sms.bnet.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SMSServiceImpl {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendSMS", targetNamespace = "http://HLimpl.sms.bnet.com/", className = "com.acec.wgt.service.sms.SendSMS")
    @ResponseWrapper(localName = "sendSMSResponse", targetNamespace = "http://HLimpl.sms.bnet.com/", className = "com.acec.wgt.service.sms.SendSMSResponse")
    public String sendSMS(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recvSMS", targetNamespace = "http://HLimpl.sms.bnet.com/", className = "com.acec.wgt.service.sms.RecvSMS")
    @ResponseWrapper(localName = "recvSMSResponse", targetNamespace = "http://HLimpl.sms.bnet.com/", className = "com.acec.wgt.service.sms.RecvSMSResponse")
    public List<String> recvSMS(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recvMTState", targetNamespace = "http://HLimpl.sms.bnet.com/", className = "com.acec.wgt.service.sms.RecvMTState")
    @ResponseWrapper(localName = "recvMTStateResponse", targetNamespace = "http://HLimpl.sms.bnet.com/", className = "com.acec.wgt.service.sms.RecvMTStateResponse")
    public List<String> recvMTState(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRestNum", targetNamespace = "http://HLimpl.sms.bnet.com/", className = "com.acec.wgt.service.sms.GetRestNum")
    @ResponseWrapper(localName = "getRestNumResponse", targetNamespace = "http://HLimpl.sms.bnet.com/", className = "com.acec.wgt.service.sms.GetRestNumResponse")
    public int getRestNum(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
